### ISSUE TITLE
rename files option?

### ISSUE THREAD

**Issue by mgutz** [egoist/kopy#5]
First, thanks for project!

Is there a way to customize the output filename? My editor goes wonky unless source file  has `.ejs` extension. Basically I'd like kopy to process `source.js.ejs` and invoke the rename option function `rename('source.js.ejs')` returning `source.js` as the output file.

More than happy to submit a PR.

**Comment by egoist** [comment]
you mean https://github.com/egoist/kopy/blob/master/README.md#move ?

**Comment by mgutz** [comment]
Apologies for wasting your time. I saw an object as the option and skipped that section.
